"""
Command line runner for the Music Recommender Simulation.

This file helps you quickly run and test your recommender.

You will implement the functions in recommender.py:
- load_songs
- score_song
- recommend_songs
"""

import os
import importlib
import json

from .recommender import load_songs, recommend_songs


def fetch_similar_songs(song_id: int, limit: int = 3) -> list:
    """Return the most similar songs from PostgreSQL if the database is available."""
    try:
        psycopg2 = importlib.import_module("psycopg2")
    except ImportError:
        return []

    db_url = os.getenv(
        "POSTGRES_URL",
        "host=localhost port=5432 dbname=music_recommender user=postgres",
    )

    query = """
        WITH query AS (
          SELECT embedding FROM songs WHERE id = %s
        )
        SELECT
          s.id,
          s.title,
          s.artist,
          s.genre,
                    s.mood,
                    s.energy,
                    s.tempo_bpm,
                    s.valence,
                    s.danceability,
                    s.acousticness,
          1 - (s.embedding <=> q.embedding) AS similarity
        FROM songs s, query q
        WHERE s.id != %s
        ORDER BY s.embedding <=> q.embedding
        LIMIT %s;
    """

    try:
        with psycopg2.connect(db_url) as conn:
            with conn.cursor() as cur:
                cur.execute(query, (song_id, song_id, limit))
                return cur.fetchall()
    except Exception:
        return []


def _fallback_song_description(song: dict) -> str:
    """Return a deterministic one-sentence song description if LLM is unavailable."""
    return (
        f"\"{song['title']}\" by {song['artist']} is a {song['mood']} {song['genre']} track "
        f"with {song['energy']:.2f} energy and {song['acousticness']:.2f} acousticness."
    )


def describe_song_with_llm(song: dict, reasons: str, similar_songs: list) -> str:
    """
    Return a one-sentence description generated by ChatGPT.
    Prompt includes the target song metadata plus top-3 similar song metadata.
    Falls back to deterministic text if API key or package is unavailable.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return _fallback_song_description(song)

    try:
        openai = importlib.import_module("openai")
    except ImportError:
        return _fallback_song_description(song)

    song_metadata = {
        "id": song.get("id"),
        "title": song.get("title"),
        "artist": song.get("artist"),
        "genre": song.get("genre"),
        "mood": song.get("mood"),
        "energy": song.get("energy"),
        "tempo_bpm": song.get("tempo_bpm"),
        "valence": song.get("valence"),
        "danceability": song.get("danceability"),
        "acousticness": song.get("acousticness"),
    }

    similar_song_metadata = [
        {
            "id": s[0],
            "title": s[1],
            "artist": s[2],
            "genre": s[3],
            "mood": s[4],
            "energy": s[5],
            "tempo_bpm": s[6],
            "valence": s[7],
            "danceability": s[8],
            "acousticness": s[9],
            "similarity": s[10],
        }
        for s in similar_songs
    ]

    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

    prompt_payload = {
        "recommendation_reasons": reasons,
        "song_metadata": song_metadata,
        "top_3_similar_song_metadata": similar_song_metadata,
        "instruction": "Write exactly one sentence that briefly describes this song and its similar tracks genre.",
    }

    try:
        client = openai.OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model=model,
            temperature=0.5,
            max_tokens=60,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a music recommendation assistant. "
                        "Produce exactly one concise sentence. No bullets. No preamble."
                    ),
                },
                {
                    "role": "user",
                    "content": json.dumps(prompt_payload, ensure_ascii=False),
                },
            ],
        )

        content = (response.choices[0].message.content or "").strip().replace("\n", " ")
        if not content:
            return _fallback_song_description(song)
        return content
    except Exception:
        return _fallback_song_description(song)


def run_profile(name: str, user_prefs: dict, songs: list, k: int = 5) -> None:
    """Print top recommendations for one named profile."""
    print(f"\n=== Profile: {name} ===")
    recommendations = recommend_songs(user_prefs, songs, k=k)
    for idx, rec in enumerate(recommendations, start=1):
        song, score, explanation = rec
        print(f"{idx}. {song['title']} — {song['artist']}")
        print(f"   Score: {score:.2f}")
        print(f"   Reasons: {explanation}")

        similar_songs = fetch_similar_songs(song["id"], limit=3)
        description = describe_song_with_llm(song, explanation, similar_songs)
        print(f"   Description: {description}")

        if similar_songs:
            print("   Next 3 most similar songs from PostgreSQL:")
            for (
                similar_id,
                title,
                artist,
                genre,
                mood,
                energy,
                tempo_bpm,
                valence,
                danceability,
                acousticness,
                similarity,
            ) in similar_songs:
                print(
                    "     - "
                    f"{title} — {artist} ({genre}, {mood}, energy {energy:.2f}, "
                    f"acousticness {acousticness:.2f}), similarity: {similarity:.4f}"
                )
        else:
            print("   Next 3 most similar songs from PostgreSQL: unavailable")
        print()


def main() -> None:
    songs = load_songs("data/songs.csv")
    print(f"Loaded songs: {len(songs)}")

    profiles = [
        (
            "High-Energy Pop",
            {
                "genre": "pop",
                "mood": "happy",
                "energy": 0.8,
                "likes_acoustic": False,
            },
        ),
        (
            "Chill Lofi",
            {
                "genre": "lofi",
                "mood": "chill",
                "energy": 0.35,
                "likes_acoustic": True,
            },
        ),
        (
            "Deep Intense Rock",
            {
                "genre": "rock",
                "mood": "intense",
                "energy": 0.92,
                "likes_acoustic": False,
            },
        ),
        (
            "Adversarial: High-Energy Sad Acoustic",
            {
                "genre": "lofi",
                "mood": "sad",
                "energy": 0.9,
                "likes_acoustic": True,
            },
        ),
        (
            "Experiment: Energy-heavy High-Energy Pop",
            {
                "genre": "pop",
                "mood": "happy",
                "energy": 0.8,
                "likes_acoustic": False,
                # Weight-shift experiment: half genre, double energy
                "w_genre": 1.0,
                "w_energy": 3.0,
            },
        ),
    ]

    for name, user_prefs in profiles:
        run_profile(name, user_prefs, songs, k=5)


if __name__ == "__main__":
    main()
